# Generated by Django 4.1.4 on 2022-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Coding', 'Coding'), ('Bible', 'Bible'), ('Exercise', 'Exercise')], default='Coding', max_length=128),
        ),
    ]
