# Generated by Django 4.1.4 on 2022-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Coding', 'Coding'), ('Bible', 'Bible'), ('Exercise', 'Exercise')], default='Generic', max_length=128),
        ),
    ]
