# Generated by Django 4.1.4 on 2022-12-21 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
