# Generated by Django 5.0.3 on 2024-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(default='Generic', max_length=128),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('notes', models.ManyToManyField(to='notes.note')),
            ],
        ),
    ]
