# Generated by Django 5.0.3 on 2024-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_tag_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='Generic', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='notes.tag'),
        ),
    ]
