# Generated by Django 5.0.3 on 2024-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_tag_notes_remove_note_tags_alter_tag_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.CharField(default='Summary', max_length=128),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
