# Generated by Django 5.0.3 on 2024-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_note_tags_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.CharField(max_length=128),
        ),
    ]
